name: SuPermission
version: 1.0.1
api-version: 1.20
author: nivcoo
main: fr.nivcoo.supermission.SuPermission
loadbefore: [ SuperiorSkyblock2 ]
permissions:
  supermission.bypass.fly:
    description: Bypass fly restrictions
    default: op